services:
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend
    networks:
      - traefik
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bingo-frontend.rule=Host(`bingo.pseudolab-devfactory.com`)"
      - "traefik.http.routers.bingo-frontend.entrypoints=websecure"
      - "traefik.http.routers.bingo-frontend.tls.certresolver=le"
      - "traefik.http.services.bingo-frontend.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_URL: ${DB_URL}
      SWAGGER_USERNAME: ${SWAGGER_USERNAME}
      SWAGGER_PASSWORD: ${SWAGGER_PASSWORD}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
    command: >
      /bin/sh -c "
        alembic upgrade head &&
        python app/start.py
      "
    networks:
      - traefik
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bingo-backend.rule=Host(`bingo.pseudolab-devfactory.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.bingo-backend.entrypoints=websecure"
      - "traefik.http.routers.bingo-backend.tls.certresolver=le"
      - "traefik.http.services.bingo-backend.loadbalancer.server.port=8000"
      - "traefik.docker.network=traefik"

networks:
  traefik:
    external: true
