import type { BingoGameLanguage } from "../Bingo/bingoGameLanguage";

export const homeCopy = {
  ko: {
    languageSetting: "언어 설정",
    languageOptions: [
      { value: "ko", label: "한국어" },
      { value: "en", label: "English" },
    ],
    statusComplete: "완료",
    statusError: "오류",
    close: "닫기",
    loadingError: "테스트 계정 목록을 불러오지 못했습니다.",
    restoreError: "Google 로그인 정보를 복구하지 못했습니다.",
    eventRequired: "행사 정보를 확인한 뒤 다시 시도해 주세요.",
    googleSessionError: "Google 로그인 세션을 확인하지 못했습니다.",
    googleLoginError: "Google 로그인 중 오류가 발생했습니다.",
    testLoginInvalid: "유효한 행사 주소에서만 테스트 로그인을 진행할 수 있습니다.",
    testLoginFailed: "테스트 계정 전환에 실패했습니다.",
    testLoginSuccess: (name: string) => `"${name}" 계정으로 전환했습니다.`,
    testLoginError: "테스트 계정 전환 중 오류가 발생했습니다.",
    testResetConfirm: "로컬 테스트 보드와 교환 기록을 처음 상태로 되돌릴까요?",
    testResetSuccess: "테스트 데이터를 처음 상태로 초기화했습니다.",
    testResetError: "테스트 데이터 초기화 중 오류가 발생했습니다.",
    testerPanelAriaLabel: "local mock tester",
    testerPanelEyebrow: "테스트 모드 계정",
    testerPanelTitle: "탭마다 다른 계정으로 바로 테스트",
    testerPanelDescription:
      "테스트 계정 로그인은 현재 탭의 `sessionStorage`를 쓰고, mock 보드와 교환 기록은 브라우저 전체에서 공유합니다. 그래서 여러 탭을 열어 두면 서로 다른 계정끼리 바로 교환 테스트를 할 수 있습니다.",
    testerRefreshLoading: "불러오는 중...",
    testerRefresh: "새로고침",
    testerResetting: "초기화 중...",
    testerReset: "테스트 초기화",
    testerBoardReady: "보드 준비 완료",
    testerBoardPending: "보드 미준비",
    testerSwitching: "전환 중...",
    testerUseCurrentTab: "이 탭으로",
    testerOpenNewTab: "새 탭 열기",
    loginPolicyTitle: "로그인 전 확인",
    loginPolicySummary:
      "Google로 계속하면 Google 계정의 이름, 이메일 주소, 계정 고유 식별자를 사용해 이 행사 참가 계정을 만듭니다. 행사 중 선택한 키워드, 빙고 보드, 진행률, 키워드 교환 기록은 빙고 진행과 행사 운영을 위해 사용됩니다.",
    requiredChecksLabel: "필수 확인 항목",
    required: "[필수]",
    terms: "서비스 이용약관",
    termsAgreement: "에 동의합니다",
    privacy: "개인정보처리방침",
    and: "및",
    eventPrivacy: "행사별 개인정보 안내",
    privacyConfirmation: "를 확인했습니다",
    loginHint: "필수 항목을 확인한 뒤 Google 로그인을 진행할 수 있습니다.",
    eventSummaryAriaLabel: "event summary",
    loginFormAriaLabel: "login form",
    notFoundEyebrow: "Public Event",
    notFoundTitle: "행사를 찾을 수 없습니다",
    notFoundDescription:
      "입력한 행사 주소로는 공개 행사 페이지를 열 수 없습니다. 주최자에게 최신 링크를 다시 확인하거나 메인 화면에서 행사 목록을 확인해 주세요.",
    eventErrorTitle: "행사 정보를 확인할 수 없습니다",
    eventErrorDescription: "행사 정보를 불러오는 중 오류가 발생했습니다. 잠시 후 다시 시도해 주세요.",
    reload: "새로고침",
    nameRequiredTitle: "이름 설정 필요",
    nameRequiredDescription: "빙고에서 사용할 이름을 먼저 설정해 주세요.",
    goToBingo: "빙고로 이동",
    setName: "이름 설정하기",
    logout: "로그아웃",
    googleSetupRequired: "Google 로그인 설정이 필요합니다.",
  },
  en: {
    languageSetting: "Language setting",
    languageOptions: [
      { value: "ko", label: "한국어" },
      { value: "en", label: "English" },
    ],
    statusComplete: "Done",
    statusError: "Error",
    close: "Close",
    loadingError: "Could not load test accounts.",
    restoreError: "Could not restore Google login information.",
    eventRequired: "Please check the event information and try again.",
    googleSessionError: "Could not verify the Google login session.",
    googleLoginError: "There was a problem with Google login.",
    testLoginInvalid: "Test login is only available from a valid event URL.",
    testLoginFailed: "Could not switch test account.",
    testLoginSuccess: (name: string) => `Switched to "${name}".`,
    testLoginError: "There was a problem switching test accounts.",
    testResetConfirm: "Reset local test boards and exchange history?",
    testResetSuccess: "Test data has been reset.",
    testResetError: "There was a problem resetting test data.",
    testerPanelAriaLabel: "local mock tester",
    testerPanelEyebrow: "Test Mode Accounts",
    testerPanelTitle: "Test with a different account per tab",
    testerPanelDescription:
      "Test account login uses this tab's `sessionStorage`, while mock boards and exchange history are shared across the browser. Open multiple tabs to test exchanges between different accounts.",
    testerRefreshLoading: "Loading...",
    testerRefresh: "Refresh",
    testerResetting: "Resetting...",
    testerReset: "Reset Test Data",
    testerBoardReady: "Board ready",
    testerBoardPending: "Board not ready",
    testerSwitching: "Switching...",
    testerUseCurrentTab: "Use here",
    testerOpenNewTab: "Open tab",
    loginPolicyTitle: "Before Login",
    loginPolicySummary:
      "Continuing with Google creates your event participant account using your Google account name, email address, and account identifier. The keywords you choose, bingo board, progress, and keyword exchange history are used for bingo progress and event operations.",
    requiredChecksLabel: "Required checks",
    required: "[Required]",
    terms: "Terms of Service",
    termsAgreement: "I agree to the",
    privacy: "Privacy Policy",
    and: "and",
    eventPrivacy: "event privacy notice",
    privacyConfirmation: "I have reviewed the",
    loginHint: "Review the required items before continuing with Google.",
    eventSummaryAriaLabel: "event summary",
    loginFormAriaLabel: "login form",
    notFoundEyebrow: "Public Event",
    notFoundTitle: "Event Not Found",
    notFoundDescription:
      "This event address cannot open a public event page. Please check the latest link with the organizer or browse events from the main page.",
    eventErrorTitle: "Could Not Load Event",
    eventErrorDescription: "There was a problem loading event information. Please try again later.",
    reload: "Reload",
    nameRequiredTitle: "Name Setup Needed",
    nameRequiredDescription: "Please set the name you want to use in bingo first.",
    goToBingo: "Go to Bingo",
    setName: "Set Name",
    logout: "Log Out",
    googleSetupRequired: "Google login setup is required.",
  },
} as const;

export const getHomeEventCategoryLabel = (
  title: string,
  language: BingoGameLanguage
) => {
  const normalizedTitle = title.trim();
  if (language === "en" && normalizedTitle === "빙고 네트워킹") {
    return "Bingo Networking";
  }

  return title;
};
