"""create umoh_id, privacy_agreed to bingo_user table

Revision ID: 1604e736a027
Revises: e3af490de067
Create Date: 2025-05-15 22:18:38.581530+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1604e736a027'
down_revision: Union[str, None] = 'e3af490de067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bingo_user", sa.Column("umoh_id", sa.Integer, nullable=True))
    op.add_column('bingo_user', sa.Column('privacy_agreed', sa.Boolean, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bingo_user", "umoh_id")
    op.drop_column('bingo_user', 'privacy_agreed')
    # ### end Alembic commands ###
