"""add rating column to bingo_user

Revision ID: 499d313460d4
Revises: ec883f25f928
Create Date: 2025-05-15 02:15:17.074215+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '499d313460d4'
down_revision: Union[str, None] = 'ec883f25f928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bingo_user', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('bingo_user', sa.Column('review', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bingo_user', 'review')
    op.drop_column('bingo_user', 'rating')
    # ### end Alembic commands ###
