"""add bingo_user

Revision ID: 5f07312a2712
Revises: ef31eeadc783
Create Date: 2025-05-06 17:15:42.482754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5f07312a2712'
down_revision: Union[str, None] = 'ef31eeadc783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bingo_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('user_email', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_table('user_word_status')
    op.add_column('bingo_interaction', sa.Column('word_id_list', sa.String(length=200), nullable=False))
    op.drop_column('bingo_interaction', 'word_id')
    op.create_unique_constraint(None, 'meta_word', ['word'])
    op.add_column('user', sa.Column('access_token', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('refresh_token', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('access_token_expires_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('refresh_token_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'refresh_token_expires_at')
    op.drop_column('user', 'access_token_expires_at')
    op.drop_column('user', 'refresh_token')
    op.drop_column('user', 'access_token')
    op.drop_constraint(None, 'meta_word', type_='unique')
    op.add_column('bingo_interaction', sa.Column('word_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('bingo_interaction', 'word_id_list')
    op.create_table('user_word_status',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('word_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('position', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'word_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('bingo_user')
    # ### end Alembic commands ###
