"""add selected_words column to bingo_user

Revision ID: e3af490de067
Revises: d146264b6756
Create Date: 2025-05-15 00:49:49.839602+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3af490de067'
down_revision: Union[str, None] = 'd146264b6756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bingo_user', sa.Column('selected_words', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bingo_user', 'selected_words')
    # ### end Alembic commands ###
