"""initial migration

Revision ID: ec883f25f928
Revises: 
Create Date: 2025-05-14 22:24:50.877737+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec883f25f928'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bingo_boards',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('board_data', sa.JSON(), nullable=False),
    sa.Column('bingo_count', sa.Integer(), nullable=False),
    sa.Column('user_interaction_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('bingo_interaction',
    sa.Column('interaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word_id_list', sa.String(length=200), nullable=False),
    sa.Column('send_user_id', sa.Integer(), nullable=False),
    sa.Column('receive_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('interaction_id')
    )
    op.create_table('bingo_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('user_email', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bingo_user')
    op.drop_table('bingo_interaction')
    op.drop_table('bingo_boards')
    # ### end Alembic commands ###
