"""feat_add_user_auth_fields

Revision ID: f39f480e350e
Revises: a4f8e02f426a
Create Date: 2026-03-10 22:46:54.142880+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f39f480e350e'
down_revision: Union[str, None] = 'a4f8e02f426a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bingo_user', sa.Column('auth_provider', sa.String(length=50), nullable=False))
    op.add_column('bingo_user', sa.Column('provider_id', sa.String(length=255), nullable=True))
    op.alter_column('bingo_user', 'user_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
    op.create_unique_constraint(None, 'bingo_user', ['user_email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bingo_user', type_='unique')
    op.alter_column('bingo_user', 'user_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
    op.drop_column('bingo_user', 'provider_id')
    op.drop_column('bingo_user', 'auth_provider')
    # ### end Alembic commands ###
