export type BingoGameLanguage = "ko" | "en";

export const BINGO_GAME_LANGUAGE_STORAGE_KEY = "event-bingo.game-language.v1";

export const readBingoGameLanguage = (
  storage: Storage | undefined,
  fallback: BingoGameLanguage = "ko"
): BingoGameLanguage => {
  const storedLanguage = storage?.getItem(BINGO_GAME_LANGUAGE_STORAGE_KEY);
  return storedLanguage === "en" || storedLanguage === "ko" ? storedLanguage : fallback;
};

export const writeBingoGameLanguage = (
  storage: Storage | undefined,
  language: BingoGameLanguage
) => {
  storage?.setItem(BINGO_GAME_LANGUAGE_STORAGE_KEY, language);
};

export const bingoGameCopy = {
  ko: {
    participantSuffix: "님",
    loadingDefaultTitle: "로딩 중입니다",
    loadingDefaultDescription: "잠시만 기다려 주세요.",
    loadingBoardTitle: "빙고 보드를 불러오고 있습니다",
    loadingBoardDescription: "저장된 보드와 교환 기록을 확인하고 있어요.",
    countdownTitle: "빙고 오픈까지 조금만 기다려 주세요",
    countdownUnits: {
      days: "일",
      hours: "시간",
      minutes: "분",
      seconds: "초",
    },
    toastCloseLabel: "알림 닫기",
    toastCloseText: "닫기",
    nameSetupTitle: "이름 설정",
    nameSetupDescription: "빙고 게임에서 사용할 이름을 입력하세요.",
    namePlaceholder: "이름을 입력하세요",
    save: "저장",
    next: "다음",
    keywordSetupTitle: "관심사 선택",
    keywordSetupDescription: (count: number) =>
      `당신의 관심사를 잘 표현할 수 있는 키워드를 ${count}개 선택하세요.`,
    keywordSetupAriaLabel: "interest keyword selection",
    setupPreparing: "준비 중...",
    setupStart: "빙고 시작하기",
    heroTitleLines: ["빙고를 채우며", "소통해봐요!"],
    previewLockedPlaceholder: "프리뷰 중에는 전송을 잠시 잠가두었어요",
    opponentSearchPlaceholder: "상대방 이름 검색",
    opponentSearchAriaLabel: "상대방 이름 검색",
    searching: "검색 중...",
    noSearchResults: "검색 결과가 없습니다.",
    send: "보내기",
    soloBadge: "개인전",
    completionRate: "빙고 완성률",
    selectedKeywordsLabel: "내가 고른 키워드",
    selectedKeywordCount: (count: number) => `${count}개`,
    noSelectedKeywords: "아직 선택한 키워드가 없어요.",
    collectedKeywords: "수집한 키워드",
    metParticipants: "만난 참가자",
    metParticipantCount: (count: number) => `${count}명`,
    sentHistoryTitle: "내가 준 사람",
    sentHistoryEmpty: "아직 내가 보낸 기록이 없어요.",
    receivedHistoryTitle: "나에게 보낸 사람",
    receivedHistoryEmpty: "아직 받은 기록이 없어요.",
    eventHomeLabel: "행사 메인으로 이동",
    participantFallback: "참가자",
    homeButton: "처음으로 돌아가기",
    notFoundTitle: "행사를 찾을 수 없습니다",
    notFoundDescription:
      "이 행사 링크로는 빙고 화면에 들어갈 수 없습니다. 주최자가 공유한 최신 행사 URL을 다시 확인해 주세요.",
    eventErrorTitle: "빙고 행사 정보를 확인할 수 없습니다",
    eventErrorDescription:
      "빙고 화면에 필요한 행사 정보를 불러오는 중 오류가 발생했습니다. 잠시 후 다시 시도해 주세요.",
    reload: "새로고침",
    previewEyebrow: "테스트 모드 프리뷰",
    previewActiveTitle: "프리뷰 중에는 보드 실시간 동기화를 잠시 멈췄어요",
    previewIdleTitle: "한칸부터 올클리어까지 화면 상태를 바로 미리볼 수 있어요",
    previewDescription: "실제 보드는 복원 버튼으로 바로 되돌릴 수 있습니다.",
    previewReset: "실전 보드 복원",
    celebrationTitle: "빙고를 완성했어요",
    celebrationCopy: (missionCount: number) =>
      `${missionCount}줄 미션을 달성했습니다. 더 많은 참가자와 키워드를 나누며 보드를 계속 채워보세요.`,
    completedLines: "완성한 줄",
    openedCells: "열린 칸",
    continue: "계속 진행하기",
    alerts: {
      boardUpdated: "새 키워드가 반영됐어요.",
      boardUpdatedTitle: "보드가 업데이트됐어요",
      previewApplied: "보드 프리뷰를 적용했습니다.",
      previewTitle: "테스트 프리뷰",
      previewCleared: "실제 보드 상태로 돌아왔습니다.",
      previewClearedTitle: "프리뷰 해제",
      selectKeywordCount: (count: number) => `관심사는 ${count}개 선택해 주세요.`,
      keywordSaveError: "키워드 저장 중 문제가 발생했습니다.",
      keywordSetupError: "초기 설정 중 문제가 발생했습니다.",
      keywordsReady: "키워드가 설정되었습니다!",
      keywordLimit: (count: number) => `관심사는 ${count}개까지만 선택할 수 있습니다.`,
      bingoLine: "빙고 한 줄을 완성했습니다! 🎉",
      nameRequired: "이름을 입력해주세요.",
      missingLogin: "로그인 정보가 없습니다.",
      nameSaveError: "이름 저장 중 문제가 발생했습니다.",
      previewLocked: "보드 프리뷰를 해제한 뒤 실제 전송을 진행해 주세요.",
      previewLockedTitle: "프리뷰가 켜져 있어요",
      selectOpponent: "상대방을 검색하여 선택해주세요.",
      selfExchange: "본인 ID가 아닌 상대방 ID를 입력해주세요.",
      duplicateExchange: "이미 같은 참가자에게 키워드를 보냈어요.",
      duplicateExchangeTitle: "이미 전송한 참가자예요",
      exchangeFailed: "키워드 교환 요청에 실패했습니다. 다시 시도해주세요.",
      exchangeSuccessTitle: "키워드를 전송했어요",
      exchangeSuccessMessage: (receiverName: string) =>
        `"${receiverName}"님에게 내 키워드를 전송했어요.`,
      unknownError: "에러가 발생했습니다. 잠시 후 다시 시도해주세요.",
    },
  },
  en: {
    participantSuffix: "",
    loadingDefaultTitle: "Loading",
    loadingDefaultDescription: "Please wait a moment.",
    loadingBoardTitle: "Loading your bingo board",
    loadingBoardDescription: "Checking your saved board and exchange history.",
    countdownTitle: "Bingo opens soon",
    countdownUnits: {
      days: "Days",
      hours: "Hours",
      minutes: "Min",
      seconds: "Sec",
    },
    toastCloseLabel: "Close notification",
    toastCloseText: "Close",
    nameSetupTitle: "Set Your Name",
    nameSetupDescription: "Enter the name you want to use in this bingo game.",
    namePlaceholder: "Enter your name",
    save: "Save",
    next: "Next",
    keywordSetupTitle: "Choose Interests",
    keywordSetupDescription: (count: number) =>
      `Choose ${count} keywords that best describe your interests.`,
    keywordSetupAriaLabel: "interest keyword selection",
    setupPreparing: "Preparing...",
    setupStart: "Start Bingo",
    heroTitleLines: ["Fill your bingo board", "and connect!"],
    previewLockedPlaceholder: "Sending is paused during preview",
    opponentSearchPlaceholder: "Search participant name",
    opponentSearchAriaLabel: "Search participant name",
    searching: "Searching...",
    noSearchResults: "No results found.",
    send: "Send",
    soloBadge: "Solo",
    completionRate: "Bingo completion",
    selectedKeywordsLabel: "My selected keywords",
    selectedKeywordCount: (count: number) => `${count}`,
    noSelectedKeywords: "No keywords selected yet.",
    collectedKeywords: "Collected keywords",
    metParticipants: "People met",
    metParticipantCount: (count: number) => `${count}`,
    sentHistoryTitle: "People I Sent To",
    sentHistoryEmpty: "No sent history yet.",
    receivedHistoryTitle: "People Who Sent To Me",
    receivedHistoryEmpty: "No received history yet.",
    eventHomeLabel: "Go to event home",
    participantFallback: "Participant",
    homeButton: "Back to Start",
    notFoundTitle: "Event not found",
    notFoundDescription:
      "This event link cannot open the bingo screen. Please check the latest event URL shared by the organizer.",
    eventErrorTitle: "Could not load bingo event",
    eventErrorDescription:
      "An error occurred while loading the event details needed for bingo. Please try again later.",
    reload: "Reload",
    previewEyebrow: "Test Mode Preview",
    previewActiveTitle: "Live board sync is paused during preview",
    previewIdleTitle: "Preview board states from one cell to all clear",
    previewDescription: "You can restore your actual board anytime.",
    previewReset: "Restore Live Board",
    celebrationTitle: "Bingo Complete",
    celebrationCopy: (missionCount: number) =>
      `You completed the ${missionCount}-line mission. Keep exchanging keywords with more participants to fill your board.`,
    completedLines: "Completed lines",
    openedCells: "Open cells",
    continue: "Continue",
    alerts: {
      boardUpdated: "New keywords were added to your board.",
      boardUpdatedTitle: "Board updated",
      previewApplied: "Board preview applied.",
      previewTitle: "Test Preview",
      previewCleared: "Returned to your live board.",
      previewClearedTitle: "Preview cleared",
      selectKeywordCount: (count: number) => `Please choose ${count} interests.`,
      keywordSaveError: "There was a problem saving your keywords.",
      keywordSetupError: "There was a problem during initial setup.",
      keywordsReady: "Keywords are set!",
      keywordLimit: (count: number) => `You can choose up to ${count} interests.`,
      bingoLine: "You completed a bingo line! 🎉",
      nameRequired: "Please enter your name.",
      missingLogin: "Login information is missing.",
      nameSaveError: "There was a problem saving your name.",
      previewLocked: "Turn off board preview before sending.",
      previewLockedTitle: "Preview is on",
      selectOpponent: "Search for and select a participant.",
      selfExchange: "Please choose another participant instead of yourself.",
      duplicateExchange: "You already sent keywords to this participant.",
      duplicateExchangeTitle: "Already sent",
      exchangeFailed: "Keyword exchange failed. Please try again.",
      exchangeSuccessTitle: "Keywords sent",
      exchangeSuccessMessage: (receiverName: string) =>
        `Sent your keywords to "${receiverName}".`,
      unknownError: "Something went wrong. Please try again later.",
    },
  },
} as const;
