name: Deploy Docker Compose to Oracle Server

on:
  push:
    branches:
      - dev
  workflow_dispatch:  # 수동 실행도 가능

jobs:
  docker-compose-up:
    runs-on: oracle

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Create .env file
        run: |
          set -e
          cat <<EOF > .env
          FRONTEND_PORT=${{ secrets.FRONTEND_PORT }}
          BACKEND_PORT=${{ secrets.BACKEND_PORT }}
          VITE_API_URL=${{ secrets.VITE_API_URL }}
          DB_ROOT=${{ secrets.DB_ROOT }}
          DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_DATABASE=${{ secrets.DB_DATABASE }}
          GUEST_FILE_PATH=${{ secrets.GUEST_FILE_PATH }}
          EOF

      - name: Build and Run with Docker Compose
        run: |
          set -e
          docker compose up -d --build
